//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prelims
{
    using System;
    using System.Collections.Generic;
    
    public partial class AuditReject
    {
        public int Id { get; set; }
        public int AuditId { get; set; }
        public int RejectedBy { get; set; }
        public System.DateTime RejectedDateTime { get; set; }
        public Nullable<int> AcceptedBy { get; set; }
        public Nullable<System.DateTime> AcceptedDateTime { get; set; }
        public string Reason { get; set; }
    
        public virtual USERINFO USERINFO { get; set; }
        public virtual Audit Audit { get; set; }
    }
}
