//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prelims
{
    using System;
    using System.Collections.Generic;
    
    public partial class AuditCheck
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AuditCheck()
        {
            this.AuditCheckCrns = new HashSet<AuditCheckCrn>();
            this.AuditCheckTasks = new HashSet<AuditCheckTask>();
            this.AuditCheckValues1 = new HashSet<AuditCheckValue>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> TaskId { get; set; }
        public Nullable<int> OfficeId { get; set; }
        public string OrderNumberSeries { get; set; }
        public string AuditCheckValues { get; set; }
    
        public virtual CRN CRN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AuditCheckCrn> AuditCheckCrns { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AuditCheckTask> AuditCheckTasks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AuditCheckValue> AuditCheckValues1 { get; set; }
    }
}
