//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prelims
{
    using System;
    using System.Collections.Generic;
    
    public partial class AuditTimeEntry
    {
        public int Id { get; set; }
        public int AuditId { get; set; }
        public int AuditTaskId { get; set; }
        public int UserId { get; set; }
        public System.DateTime StartTime { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
        public bool IsInprogress { get; set; }
    
        public virtual AuditTask AuditTask { get; set; }
        public virtual AuditTimeEntry AuditTimeEntries1 { get; set; }
        public virtual AuditTimeEntry AuditTimeEntry1 { get; set; }
        public virtual USERINFO USERINFO { get; set; }
        public virtual Audit Audit { get; set; }
    }
}
