//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prelims
{
    using System;
    using System.Collections.Generic;
    
    public partial class AuditErrorType
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public int AuditErrorCategoryId { get; set; }
        public bool IsCritical { get; set; }
    
        public virtual AuditErrorCategory AuditErrorCategory { get; set; }
    }
}
