//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prelims
{
    using System;
    using System.Collections.Generic;
    
    public partial class Audit
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Audit()
        {
            this.AuditDocuments = new HashSet<AuditDocument>();
            this.AuditHolds = new HashSet<AuditHold>();
            this.AuditRejects = new HashSet<AuditReject>();
            this.AuditTimeEntries = new HashSet<AuditTimeEntry>();
            this.AuditUpdates = new HashSet<AuditUpdate>();
            this.AuditErrorJsons = new HashSet<AuditErrorJson>();
        }
    
        public int Id { get; set; }
        public string OrderNo { get; set; }
        public string OwnerNames { get; set; }
        public string PropertyAddress { get; set; }
        public string APNNo { get; set; }
        public int RequestTypeId { get; set; }
        public int StatusId { get; set; }
        public int TaskId { get; set; }
        public Nullable<int> SenderId { get; set; }
        public int CrnId { get; set; }
        public string RequestedByEmailId { get; set; }
        public string ClientInstructions { get; set; }
        public Nullable<int> CheckOwnerSearchCount { get; set; }
        public Nullable<bool> CheckDirectHitUploaded { get; set; }
        public Nullable<System.DateTime> UploadDateTime { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<int> UserCreated { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public Nullable<int> UserModified { get; set; }
        public Nullable<bool> IsQcRequired { get; set; }
        public Nullable<bool> EffectiveDateChanged { get; set; }
        public Nullable<bool> AnyChangeInVesting { get; set; }
        public Nullable<bool> AnyUpdateOnTaxInformation { get; set; }
        public Nullable<bool> AnyUpdateOnNewPIDocs { get; set; }
        public Nullable<bool> AnyUpdateOnNewGIDocs { get; set; }
        public Nullable<bool> DidYouReviewTwentyFourMonthChainOfTitle { get; set; }
        public Nullable<bool> DidYouUploadPrelimAndSPToSmartView { get; set; }
        public Nullable<bool> DidYouSendCompletionEmailToClient { get; set; }
        public string County { get; set; }
        public bool IsRushOrder { get; set; }
        public string RushOrderComments { get; set; }
        public Nullable<int> UserAssigned { get; set; }
        public string OrderMovementComments { get; set; }
        public string ReasonToAccept { get; set; }
        public string ReasonToAcceptCompletedOrder { get; set; }
        public string CWLTTitleOfficeName { get; set; }
        public string CWLTTitleOfficerName { get; set; }
        public Nullable<bool> AnyPostingFoundInPIGI { get; set; }
        public Nullable<System.DateTime> AmendmentDate { get; set; }
        public Nullable<int> TitleOrderId { get; set; }
    
        public virtual CRN CRN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AuditDocument> AuditDocuments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AuditHold> AuditHolds { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AuditReject> AuditRejects { get; set; }
        public virtual AuditRequestType AuditRequestType { get; set; }
        public virtual AuditSender AuditSender { get; set; }
        public virtual AuditStatus AuditStatus { get; set; }
        public virtual AuditTask AuditTask { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AuditTimeEntry> AuditTimeEntries { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AuditUpdate> AuditUpdates { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AuditErrorJson> AuditErrorJsons { get; set; }
    }
}
