//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prelims
{
    using System;
    using System.Collections.Generic;
    
    public partial class CRN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CRN()
        {
            this.AuditSenders = new HashSet<AuditSender>();
            this.Audits = new HashSet<Audit>();
            this.AuditChecks = new HashSet<AuditCheck>();
        }
    
        public int CRNID { get; set; }
        public string CRNNAME { get; set; }
        public string CRNNO { get; set; }
        public string DESCP { get; set; }
        public string FTPADDRESS { get; set; }
        public string USERNAME { get; set; }
        public string PASSWORD { get; set; }
        public string DESTINATIONPATH { get; set; }
        public string SOURCEPATH { get; set; }
        public string LOCALPATH { get; set; }
        public string MAILTO { get; set; }
        public string MAILCC { get; set; }
        public string MAILBCC { get; set; }
        public Nullable<int> ALERTDURATION { get; set; }
        public Nullable<int> ORDERSTATUSDURATION { get; set; }
        public string MAILTOFORREJECT { get; set; }
        public string MAILCCFORREJECT { get; set; }
        public string AUTODOWNLOADSTATUS { get; set; }
        public string CRNDISPLAYNAME { get; set; }
        public string PolicyKeyDisplayName { get; set; }
        public string PayoffDisplayName { get; set; }
        public string GroupName { get; set; }
        public Nullable<bool> IsVisibleInMainApplication { get; set; }
        public string LegalVerificationEmailAddress { get; set; }
        public string LegalVerificationEmailCCAddress { get; set; }
        public string NoOpenDOTEmailAddress { get; set; }
        public string NoOpenDOTCCEmailAddress { get; set; }
        public string PropertyTypeEmailAddress { get; set; }
        public string PropertyTypeCCEmailAddress { get; set; }
        public string EasementsEmailAddress { get; set; }
        public string EasementsCCEmailAddress { get; set; }
        public string HoldCCEmailAddresses { get; set; }
        public string HoldToEmailAddresses { get; set; }
        public string RejectCCEmailAddresses { get; set; }
        public string RejectToEmailAddresses { get; set; }
        public string HoldEmailTo { get; set; }
        public string RejectEmailTo { get; set; }
        public string HoldEmailToOct { get; set; }
        public string HoldEmailCcOct { get; set; }
        public string ErrorEmailTo { get; set; }
        public string CourtOrderEmailTo { get; set; }
        public string DailyProductionEmailTo { get; set; }
        public string ForeclosureOrderEmailTo { get; set; }
        public string CttoxnardCc { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AuditSender> AuditSenders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Audit> Audits { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AuditCheck> AuditChecks { get; set; }
    }
}
