//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prelims
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FntEntities : DbContext
    {
        public FntEntities()
            : base("name=FntEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CRN> CRNs { get; set; }
        public virtual DbSet<AuditDocument> AuditDocuments { get; set; }
        public virtual DbSet<AuditHoldReason> AuditHoldReasons { get; set; }
        public virtual DbSet<AuditHold> AuditHolds { get; set; }
        public virtual DbSet<AuditRejectReason> AuditRejectReasons { get; set; }
        public virtual DbSet<AuditReject> AuditRejects { get; set; }
        public virtual DbSet<AuditRequestType> AuditRequestTypes { get; set; }
        public virtual DbSet<AuditSender> AuditSenders { get; set; }
        public virtual DbSet<AuditStatus> AuditStatuses { get; set; }
        public virtual DbSet<AuditTask> AuditTasks { get; set; }
        public virtual DbSet<AuditTimeEntry> AuditTimeEntries { get; set; }
        public virtual DbSet<AuditUpdate> AuditUpdates { get; set; }
        public virtual DbSet<UserFilter> UserFilters { get; set; }
        public virtual DbSet<USERINFO> USERINFOes { get; set; }
        public virtual DbSet<USERROLE> USERROLES { get; set; }
        public virtual DbSet<Audit> Audits { get; set; }
        public virtual DbSet<STATECOUNTY> STATECOUNTies { get; set; }
        public virtual DbSet<AuditErrorCategory> AuditErrorCategories { get; set; }
        public virtual DbSet<AuditErrorJson> AuditErrorJsons { get; set; }
        public virtual DbSet<AuditErrorType> AuditErrorTypes { get; set; }
        public virtual DbSet<AuditCheckCrn> AuditCheckCrns { get; set; }
        public virtual DbSet<AuditCheck> AuditChecks { get; set; }
        public virtual DbSet<AuditCheckTask> AuditCheckTasks { get; set; }
        public virtual DbSet<AuditCheckValue> AuditCheckValues { get; set; }
        public virtual DbSet<CWTRequestedOffice> CWTRequestedOffices { get; set; }
        public virtual DbSet<CWTTitleOfficerName> CWTTitleOfficerNames { get; set; }
        public virtual DbSet<UserCrn> UserCrns { get; set; }
    }
}
