//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prelims
{
    using System;
    using System.Collections.Generic;
    
    public partial class STATECOUNTY
    {
        public int COUNTYID { get; set; }
        public string STATE { get; set; }
        public Nullable<int> SEQ { get; set; }
        public string COUNTYNAME { get; set; }
        public string TaxURL { get; set; }
    }
}
