//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prelims
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserFilter
    {
        public int Id { get; set; }
        public string FilerCode { get; set; }
        public string FilterJson { get; set; }
        public int UserId { get; set; }
    
        public virtual USERINFO USERINFO { get; set; }
    }
}
