//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prelims
{
    using System;
    using System.Collections.Generic;
    
    public partial class USERINFO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public USERINFO()
        {
            this.AuditHolds = new HashSet<AuditHold>();
            this.AuditRejects = new HashSet<AuditReject>();
            this.AuditTimeEntries = new HashSet<AuditTimeEntry>();
            this.AuditUpdates = new HashSet<AuditUpdate>();
            this.UserFilters = new HashSet<UserFilter>();
        }
    
        public int USERID { get; set; }
        public string USERNAME { get; set; }
        public string FULLNAME { get; set; }
        public string PASSWORD { get; set; }
        public string FIRSTNAME { get; set; }
        public string LASTNAME { get; set; }
        public Nullable<int> VENDORID { get; set; }
        public Nullable<int> CUSTOMERID { get; set; }
        public int ROLEID { get; set; }
        public Nullable<System.DateTime> DT_ADDED { get; set; }
        public Nullable<System.DateTime> LOGINDATE { get; set; }
        public Nullable<byte> ISACTIVE { get; set; }
        public string EMAIL { get; set; }
        public string USERTYPE { get; set; }
        public string ASSIGNCUSTOMER { get; set; }
        public Nullable<byte> ISDELETED { get; set; }
        public bool ISREVIEWER { get; set; }
        public Nullable<bool> IsSupportingServicesReviewer { get; set; }
        public string LOCATION { get; set; }
        public Nullable<int> TitleOrderRoleId { get; set; }
        public bool IsAllowedToAccept { get; set; }
        public bool IsAllowedToChangeOffice { get; set; }
        public bool IsAllowedToMoveToPreviousTask { get; set; }
        public bool IsAllowedToChangeOrderType { get; set; }
        public bool IsAllowedToChangePriority { get; set; }
        public bool IsAllowedToEditRequiredTasks { get; set; }
        public bool IsSupportingServicesReviewerTwo { get; set; }
        public bool IsSupportingServicesProcessor { get; set; }
        public int UserLevel { get; set; }
        public string PrimaryOperationName { get; set; }
        public bool IsAllowedToViewInprogressOrders { get; set; }
        public Nullable<int> ReportingManagerId { get; set; }
        public string EmployeeCode { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AuditHold> AuditHolds { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AuditReject> AuditRejects { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AuditTimeEntry> AuditTimeEntries { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AuditUpdate> AuditUpdates { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserFilter> UserFilters { get; set; }
    }
}
